### ISSUE TITLE
VJ's UI improvements

### ISSUE THREAD

**Issue by mcphail** [openhealthcare/android-nice-guidance#3]
I've merged them to my fork (which is basically a slightly cleaned up version) and they work well. Search is broken so I'll have a look at that.

What is the origin of the new icons and are they available under a suitable licence? Do they require attribution?

**Comment by VJ911** [comment]
Ideally I want to be able to filter on 3 things:
1.  Text entry in searchbox against filename
2.  Pressing the 1st icon toggles filtering by source
3.  Pressing the 2nd icon toggles filtering by category

http://dryicons.com/free-icons/preview/medical-icons/
http://www.androidicons.com/freebies.php

SInce I fixed the layout to be density independant, we can probably draw our own.
Or pull from: http://www.iconarchive.com/
